# Generated by Django 4.0.6 on 2022-11-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_imagen_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='', upload_to='./static/productos/imagenes'),
        ),
    ]
